Added 5 Jasmine tests for String.Trim function.
byte-pushers/bytepushers-js-string-extensions pull request #2
Opened 2019-01-15 18:30 UTC by agamble33

Added four more unit tests for trim method

2019-01-16 20:23 UTC, tonte-pouncil requested changes

2019-01-16 20:23 UTC, tonte-pouncil commented on src/main/javascript/software.bytepushers.string.extensions.js
> +        return this.replace(/^\s+|\s+$/g, '');
Remove space at the end of line.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +define(['bytepushers'], function (BytePushers) {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +    describe("String extension tests:", function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('will trim whitespace correctly', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('trim white space before and after string but not space between letters', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('trim white space before and after string but not space between words', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('trim white space after string but not space between words', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('white space will not be trimmed if there is no white space', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can tell if a string includes a string', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can tell if a string does not include a string', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format a sentence into camel case', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format a sentence into camel case', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format a sentence into camel case with a single letter word', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format a string properly', function () {
Remove space between function and open parentheses.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var testString = " a b c ";
Rename testString variable to stringUnderTest.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var testString = " Donkey Kong ";
Rename testString variable to stringUnderTest.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var testString = "Duck Hunt ";
Rename testString variable to stringUnderTest.

2019-01-16 20:23 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var testString = "Ness";
Rename testString variable to stringUnderTest.

2019-01-16 22:24 UTC, tonte-pouncil approved these changes

2019-01-17 00:37 UTC, closed without merging

2019-01-17 00:37 UTC, ocampd1 commented
Already merged.