Features/string camel case test
byte-pushers/bytepushers-js-string-extensions pull request #5
Opened 2019-01-15 19:19 UTC by agamble33

Added one method test, testing out camelCase

2019-01-16 14:32 UTC, agamble33 reviewed
Please edit spaces between variables, and reveiw expected results for tests, and what you want the outcome to be.

2019-01-16 20:21 UTC, tonte-pouncil requested changes

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('will stay the same', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +        it('will minimize first letter of word', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('will keep first letter of word minimized, capitalize first letter of second word and condense', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('will minimize capital letter of first word and condense', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('will minimize first and second letters of first word and keep capitalize on second word and condense', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('will minimize first and second letters of first word and keep capital on second word and condense', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('will trim whitespace correctly', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('will trim whitespace correctly', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +
Remove empty line.

2019-01-16 22:16 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +
done

2019-01-16 22:16 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +
done

2019-01-16 22:16 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +            it('will trim whitespace correctly', function () {
auto reformat puts space between function ()

2019-01-16 22:17 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +
done

2019-01-16 22:17 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +
done

2019-01-16 22:17 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +
done

2019-01-16 22:18 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +
done

2019-01-16 22:18 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +
done

2019-01-16 22:19 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +
done

2019-01-16 22:23 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +            it('will minimize first and second letters of first word and keep capital on second word and condense', function () {
Reformat option on webstorm puts the space back between function ()

2019-01-16 22:24 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +
done

2019-01-18 18:51 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +            it('will stay the same', function () {
Removed space between function and open parentheses.

2019-01-18 18:52 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Empty line removed.

2019-01-18 18:53 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Empty line removed.

2019-01-18 18:53 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +        it('will minimize first letter of word', function () {
Removed space between function and open parentheses.

2019-01-18 18:54 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:55 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +            it('will keep first letter of word minimized, capitalize first letter of second word and condense', function () {
Removed space between function and open parentheses.

2019-01-18 18:56 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +            it('will minimize capital letter of first word and condense', function () {
Removed space between function and open parentheses.

2019-01-18 18:57 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +            it('will minimize first and second letters of first word and keep capitalize on second word and condense', function () {
Removed space between function and open parentheses.

2019-01-18 18:57 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:58 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:58 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:59 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:59 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:59 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:59 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:59 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:59 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:59 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:59 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 18:59 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-01-18 19:00 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +
Removed empty line.

2019-06-28 20:23 UTC, merged