created another test case for format
byte-pushers/bytepushers-js-string-extensions pull request #6
Opened 2019-01-15 19:38 UTC by agamble33

Added a test for format method pending error

2019-01-15 21:53 UTC, agamble33 reviewed
Created three different dynamic tests one with three dynamic arguments. One with no arguments and one with two.

2019-01-16 15:05 UTC, ocampd1 requested changes
Needs actualResult on line in order to reflect with code.

2019-01-16 15:05 UTC, ocampd1 commented on src/test/javascript/stringExtensionSpec.js
> +                expect(result).toBe(testStr); // testStr = "I'm a powerful frontend developer";
Needs actualResult on line in order to reflect with code.

2019-01-16 20:21 UTC, tonte-pouncil requested changes

2019-01-16 20:21 UTC, tonte-pouncil commented on src/main/javascript/software.bytepushers.string.extensions.js
> +     * @param {...string} string - first argument is the string template to be formatted.  The remaining arguments are the format/dynamic items (e.g. "{0}")
Let change the documentation to say: The remaining arguments will be dynamically injected into template variable placeholders.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format a sentence into camel case with a single letter word', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format a string properly', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format a sentence into camel case', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format a sentence into camel case', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can tell if a string does not include a string', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can tell if a string includes a string', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +    describe("String extension tests:", function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('will trim whitespace correctly', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format two dynamic variables into template.', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format three dynamic variables into template.', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format with no dynamic variables into template.', function () {
Remove space between function and open parentheses.

2019-01-16 20:21 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can format one dynamic variables into template.', function () {
Remove space between function and open parentheses.

2019-01-16 22:11 UTC, tonte-pouncil approved these changes

2019-01-16 22:13 UTC, merged