Features/string includes test
byte-pushers/bytepushers-js-string-extensions pull request #7
Opened 2019-01-15 19:48 UTC by ocampd1

Created "counter" test on includes-method.

2019-01-16 14:51 UTC, agamble33 requested changes
Please review and delete space between variables and expect

2019-01-16 15:59 UTC, agamble33 requested changes
The referenced string could be rewritten to make more understandable or add a comment on the unit test.

2019-01-16 15:59 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                var result = testStr.includes("counter");
The referenced string could be rewritten to make more understandable or add a comment on the unit test.

2019-01-16 20:20 UTC, tonte-pouncil requested changes

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var result = " happytime".trim();
Please create stringUnderTest like so: `var stringUnderTest = " happytime";` 
And then use like so: `var actualResult = stringUnderTest.trim();`

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var frontTrimTest = "ABC";
Rename `frontTrimTest` to `stringUnderTest`.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var frontTrimTest = " ABC";
Rename `frontTrimTest` to `stringUnderTest`.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var noSpaceTrimTest = " ABC ";
Rename `noSpaceTrimTest` to `stringUnderTest`.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can tell if a string includes a string', function () {
Remove space between function and open parentheses.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it('can tell if a string does not include a string', function () {
Remove space between function and open parentheses.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var result = testStr.includes("counter");
Set up the normal stringUnderTest, actualResult, and expectedResult variables.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var result = testStr.includes(" ");
Set up the normal stringUnderTest, actualResult, and expectedResult variables.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                var result = testStr.includes("");
Set up the normal stringUnderTest, actualResult, and expectedResult variables.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +            it("", function () {
Please provide a good test description.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                    var result = "Hello this is a sentence.".toCamelCase();
Set up the normal stringUnderTest, actualResult, and expectedResult variables.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                    var result = "Hello world".toCamelCase().toNormalCase();
Set up the normal stringUnderTest, actualResult, and expectedResult variables.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                    var result = "Hello this is a sentence".toCamelCase().toNormalCase();
Set up the normal stringUnderTest, actualResult, and expectedResult variables.

2019-01-16 20:20 UTC, tonte-pouncil commented on src/test/javascript/stringExtensionSpec.js
> +                it('can format a string properly', function () {
Set up the normal stringUnderTest, actualResult, and expectedResult variables.

2019-01-17 15:55 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                var result = " happytime".trim();
updated

2019-01-17 15:57 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                var frontTrimTest = "ABC";
done

2019-01-17 15:58 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                var frontTrimTest = " ABC";
done

2019-01-17 15:59 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                var noSpaceTrimTest = " ABC ";
done

2019-01-17 15:59 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +            it('can tell if a string includes a string', function () {
reformat keeps space

2019-01-17 15:59 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +            it('can tell if a string does not include a string', function () {
done

2019-01-17 17:39 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +            it("", function () {
done updated

2019-01-17 17:39 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                var result = testStr.includes(" ");
done

2019-01-17 17:39 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                var result = testStr.includes("");
done

2019-01-17 22:00 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                    var result = "Hello this is a sentence.".toCamelCase();
done

2019-01-17 22:00 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                    var result = "Hello world".toCamelCase().toNormalCase();
done

2019-01-17 22:00 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                    var result = "Hello this is a sentence".toCamelCase().toNormalCase();
done

2019-01-17 22:01 UTC, agamble33 commented on src/test/javascript/stringExtensionSpec.js
> +                it('can format a string properly', function () {
done

2019-01-18 18:50 UTC, agamble33 approved these changes

2019-01-18 18:54 UTC, tonte-pouncil approved these changes

2019-01-18 19:19 UTC, closed without merging